name: Contracts package workflow

on:
  push:
    branches: [ "main" ]
    paths:
    - 'Chapter-3-microservice-extraction/Contracts/Src/Fitnet.Contracts.IntegrationEvents/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'Chapter-3-microservice-extraction/Contracts/Src/Fitnet.Contracts.IntegrationEvents/**'

env:
  CHAPTER_DIR: 'Chapter-3-microservice-extraction/Contracts/Src/Fitnet.Contracts.IntegrationEvents'

jobs:
  build:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Add GitHub NuGet Source
      run: |
        dotnet nuget add source --username $OWNER --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$OWNER/index.json"
        dotnet nuget list source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OWNER: ${{ github.repository_owner }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  pack:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Pack and Publish
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Pack Project
      run: dotnet pack Fitnet.Contracts.IntegrationEvents.csproj -c Release 
    - name: Prepare Packages
      run: dotnet nuget add source --username meaboutsoftware --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/meaboutsoftware/index.json"
    - name: Publish Packages
      run: dotnet nuget push "Fitnet.Contracts.IntegrationEvents/bin/Release/EvolutionaryArchitecture.Fitnet.Contracts.IntegrationEvents.*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
