name: Chapter 3 package workflow

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Chapter-3-microservice-extraction/Fitnet.Common/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Chapter-3-microservice-extraction/Fitnet.Common/**'

env:
  CHAPTER_DIR: 'Chapter-3-microservice-extraction/Fitnet.Common'

jobs: 
  build:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        
  test:
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Test
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test

  pack: 
    defaults:
      run:
        working-directory: ${{ env.CHAPTER_DIR }}
    runs-on: ubuntu-latest
    name: Pack and Publish
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      - name: Pack Projects
        run: |
          mkdir nupkgs
          dotnet pack Fitnet.Common.Api/Fitnet.Common.Api.csproj -c Release -o ./nupkgs
          dotnet pack Fitnet.Common.Core/Fitnet.Common.Core.csproj -c Release -o ./nupkgs
          dotnet pack Fitnet.Common.Infrastructure/Fitnet.Common.Infrastructure.csproj -c Release -o ./nupkgs

      - name: Prepare Packages
        run: run: dotnet nuget add source --username meaboutsoftware --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/meaboutsoftware/index.json"

      - name: Publish Packages
        run: |
          dotnet nuget push "./nupkgs/Fitnet.Common.Api.*.nupkg" --source "github"
          dotnet nuget push "./nupkgs/Fitnet.Common.Core.*.nupkg" --source "github"
          dotnet nuget push "./nupkgs/Fitnet.Common.Infrastructure.*.nupkg" --source "github"